(function(){'use strict';const TOKEN_KEY='agent_backup_token';const storage=window.sessionStorage;const Api={
getToken(){return storage.getItem(TOKEN_KEY)||''},setToken(t){t?storage.setItem(TOKEN_KEY,t):storage.removeItem(TOKEN_KEY)},clearToken(){storage.removeItem(TOKEN_KEY)},headers(extra){const h=Object.assign({'Content-Type':'application/json'},extra||{});const t=this.getToken();if(t)h['x-auth-token']=t;return h},
async request(method,path,body,opt){const o=Object.assign({method,headers:this.headers()},opt||{});if(body!==undefined)o.body=JSON.stringify(body);const r=await fetch(path,o);let d={};try{d=await r.json()}catch(e){}if(r.status===401){this.clearToken();if(!path.includes('/api/auth/'))window.App&&window.App.showLogin('登录已过期，请重新登录')}if(!r.ok){const e=new Error(d.error||('HTTP '+r.status));e.status=r.status;e.data=d;throw e}return d},get(p){return this.request('GET',p)},post(p,b){return this.request('POST',p,b)},patch(p,b){return this.request('PATCH',p,b)},
authStatus(){return this.get('/api/auth/status')},login(p){return this.post('/api/auth/login',{password:p})},setup(p){return this.post('/api/auth/setup',{password:p})},logout(password){return this.post('/api/auth/logout',{password})},changePassword(o,n){return this.post('/api/auth/change-password',{oldPassword:o,newPassword:n})},check(){return this.get('/api/auth/check')},info(){return this.get('/api/info')},health(){return this.get('/api/health')},
config(){return this.get('/api/config')},saveConfig(c){return this.post('/api/config',c)},templates(){return this.get('/api/config/templates')},recommendedConfig(){return this.get('/api/config/recommended')},exportConfig(){location.href='/api/config/export?token='+encodeURIComponent(this.getToken())},importConfig(c){return this.post('/api/config/import',c)},
backupStatus(){return this.get('/api/backup/status')},runBackup(){return this.post('/api/backup/run',{})},precheck(){return this.post('/api/backup/precheck',{})},backups(q){return this.get('/api/backup/list'+(q||''))},backupDetail(id){return this.get('/api/backup/detail/'+encodeURIComponent(id))},archiveFiles(id,password){const q=password?'?password='+encodeURIComponent(password):'';return this.get('/api/backup/files/'+encodeURIComponent(id)+q)},download(id){location.href='/api/backup/download/'+encodeURIComponent(id)+'?token='+encodeURIComponent(this.getToken())},importBackup(file){return fetch('/api/backup/import',{method:'POST',headers:{'x-auth-token':this.getToken(),'x-import-filename':encodeURIComponent(file.name),'x-source-id':'imported','x-source-name':encodeURIComponent('手动导入')},body:file}).then(async r=>{const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'导入失败');return d})},
protect(id,on){return this.post('/api/backup/protect/'+encodeURIComponent(id),{protected:on})},updateMeta(id,patch){return this.patch('/api/backup/meta/'+encodeURIComponent(id),patch)},moveTrash(id){return this.post('/api/backup/trash/'+encodeURIComponent(id),{})},trash(){return this.get('/api/backup/trash/list')},trashStats(){return this.get('/api/backup/trash/stats')},restoreTrash(id){return this.post('/api/backup/trash/restore/'+encodeURIComponent(id),{})},deleteTrash(id,force){return this.post('/api/backup/trash/delete/'+encodeURIComponent(id),{confirm:'DELETE',forceProtected:!!force})},emptyTrash(force){return this.post('/api/backup/trash/empty',{confirm:'EMPTY',forceProtected:!!force})},cleanupTrash(days){return this.post('/api/backup/trash/cleanup',{days})},retentionRun(){return this.post('/api/backup/retention/run',{})},
scanLarge(path,limit){return this.post('/api/backup/scan/large-files',{path:path||'',limit:limit||50})},wizardScan(path){return this.post('/api/backup/wizard/scan',{path})},wizardEstimate(path,excludes){return this.post('/api/backup/wizard/estimate',{path,excludes})},wizardRun(path,excludes,name){return this.post('/api/backup/wizard/run',{path,excludes,name:name||'备份向导'})},recommendedExcludes(){return this.get('/api/backup/recommended/excludes')},sizeAnomaly(sourceId,currentSize){return this.post('/api/backup/size/anomaly',{sourceId,currentSize:currentSize||0})},
history(){return this.get('/api/history?limit=100')},audit(){return this.get('/api/audit/list?limit=200')},logs(type,lines){return this.get('/api/logs?type='+encodeURIComponent(type||'server')+'&lines='+encodeURIComponent(lines||200))},
storageInfo(){return this.get('/api/storage/info')},validateStorage(root,create){return this.post('/api/storage/validate',{root,create:!!create})},saveStorage(o){return this.post('/api/storage/save',o)},organizeStorage(){return this.post('/api/storage/organize',{})},
notifyConfig(){return this.get('/api/notify/config')},saveNotify(notify){return this.post('/api/notify/config',{notify})},testNotify(message){return this.post('/api/notify/test',{message})},
restoreList(){return this.get('/api/restore/list')},verifyRestore(id){return this.get('/api/restore/verify/'+encodeURIComponent(id))},previewRestore(id,targetPath,password){return this.post('/api/restore/preview',{id,targetPath,password:password||''})},executeRestore(id,targetPath,password){return this.post('/api/restore/execute',{id,targetPath,password:password||'',confirm:'YES'})},restoreFile(id,member,targetPath,password){return this.post('/api/restore/file',{id,member,targetPath,password:password||'',confirm:'YES'})},
qwenpawAnalyze(root){return this.post('/api/qwenpaw/analyze',{root})}
};window.Api=Api;})();
