(function(){
'use strict';
const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const state={
  config:null,backups:[],restoreBackups:[],status:{},info:{},setupMode:false,current:'home',
  agents:null,lastBackupRun:null,polling:false
};
const REC_SOURCES=[
  {id:'qwenpaw-memory',name:'长期记忆 MEMORY.md',path:'/vol3/@appshare/com.dustinky.qwenpaw/.qwenpaw/workspaces',enabled:true,include:['MEMORY.md','memory/*.md','*/MEMORY.md','*/memory/*.md'],exclude:['node_modules','.git','*.log','*.tmp']},
  {id:'qwenpaw-skills',name:'技能 skills/',path:'/vol3/@appshare/com.dustinky.qwenpaw/.qwenpaw/workspaces',enabled:true,include:['skills/**'],exclude:['node_modules','.git','*.log','*.tmp']},
  {id:'qwenpaw-config',name:'智能体配置',path:'/vol3/@appshare/com.dustinky.qwenpaw/.qwenpaw/workspaces',enabled:true,include:['agent.json','PROFILE.md','SOUL.md','AGENTS.md','*/agent.json','*/PROFILE.md','*/SOUL.md','*/AGENTS.md'],exclude:['node_modules','.git','*.log','*.tmp']}
];
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function fmtSize(n){n=Number(n||0);if(!n)return'0 B';const u=['B','KB','MB','GB','TB'];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return(n>=10?Math.round(n):n.toFixed(1))+' '+u[i]}
function fmtTime(v){if(!v)return'-';let d;if(typeof v==='number')d=new Date(v<1e12?v*1000:v);else d=new Date(v);return isNaN(d)?esc(v):d.toLocaleString('zh-CN',{hour12:false})}
function toast(msg,type='info'){const t=$('#toast');if(!t)return;t.textContent=msg;t.className='toast '+type;setTimeout(()=>t.classList.add('hidden'),2600);t.classList.remove('hidden')}
function showBanner(msg,type='warn'){const b=$('#banner');if(!b)return;b.textContent=msg;b.className='banner '+type;b.classList.remove('hidden')}
function hideBanner(){const b=$('#banner');if(b)b.classList.add('hidden')}
function modal(html){$('#modal-content').innerHTML=html;$('#modal').classList.remove('hidden')}
function closeModal(){$('#modal').classList.add('hidden')}
function togglePwd(id){const el=$('#'+id);if(el)el.type=el.type==='password'?'text':'password'}
function clone(o){return JSON.parse(JSON.stringify(o||{}))}
function allSources(){return (state.config&&state.config.sources)||[]}
function enabledSources(){return allSources().filter(s=>s.enabled)}
function backupId(b){return b&&String(b.id||b.name||b.filename||'')}
function sourceLabel(s){return `<b>${esc(s.name||s.id)}</b><small>${esc(s.path||'')}</small>`}
function cronToUi(cron){const a=String(cron||'0 3 * * *').trim().split(/\s+/);const min=a[0]||'0',hour=a[1]||'3',dom=a[2]||'*',dow=a[4]||'*';$('#schedule-time').value=String(hour).padStart(2,'0')+':'+String(min).padStart(2,'0');if(dom!=='*'){$('#schedule-frequency').value='monthly';$('#schedule-day').value=Math.max(1,Math.min(28,parseInt(dom)||1))}else if(dow!=='*'){$('#schedule-frequency').value='weekly';$('#schedule-weekday').value=String(parseInt(dow)||0)}else $('#schedule-frequency').value='daily';updateScheduleFields()}
function uiToCron(){const [h,m]=($('#schedule-time').value||'03:00').split(':').map(x=>parseInt(x,10)||0);const f=$('#schedule-frequency').value;if(f==='weekly')return `${m} ${h} * * ${$('#schedule-weekday').value}`;if(f==='monthly')return `${m} ${h} ${Math.max(1,Math.min(28,parseInt($('#schedule-day').value)||1))} * *`;return `${m} ${h} * * *`}
function describeSchedule(){const f=$('#schedule-frequency').value,t=$('#schedule-time').value||'03:00';if(f==='weekly')return `每周${'日一二三四五六'[parseInt($('#schedule-weekday').value)||0]} ${t} 自动备份`;if(f==='monthly')return `每月 ${$('#schedule-day').value||1} 日 ${t} 自动备份`;return `每天 ${t} 自动备份`}
function updateScheduleFields(){const wf=$('#weekly-wrap'),mf=$('#monthly-wrap'),p=$('#schedule-preview');if(wf)wf.classList.toggle('hidden',$('#schedule-frequency').value!=='weekly');if(mf)mf.classList.toggle('hidden',$('#schedule-frequency').value!=='monthly');if(p)p.textContent=($('#schedule-enabled').checked?'已开启：':'未开启：')+describeSchedule()}
function pageInfo(id){return {home:['首页','备份、定时、恢复'],backup:['备份','选择内容，立即备份一次。'],schedule:['定时','自动备份时间和内容。'],restore:['恢复','选择备份，确认后恢复。'],agents:['智能体','查看当前保护对象。'],more:['更多','备份库、存储、通知和日志。']}[id]||['首页','']}
function go(id){state.current=id;$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===id));const [t,s]=pageInfo(id);$('#page-title').textContent=t;$('#page-subtitle').textContent=s;const side=$('.side');if(side)side.classList.remove('open');loadPage(id).catch(e=>toast(e.message,'error'))}
async function loadPage(id){if(['home','restore','more'].includes(id))await loadBackups();if(id==='restore')await loadRestore();if(id==='agents')await loadAgents();if(id==='more')await loadLogs();renderAll()}
function showLogin(msg){$('#main-page').classList.add('hidden');$('#login-page').classList.remove('hidden');if(msg)$('#login-hint').textContent=msg}
function showMain(){$('#login-page').classList.add('hidden');$('#main-page').classList.remove('hidden')}
async function initAuth(){try{const s=await Api.authStatus();state.setupMode=!!s.needsPasswordSetup;$('#login-password2').classList.toggle('hidden',!state.setupMode);$('#login-btn').textContent=state.setupMode?'设置密码并进入':'进入';$('#login-hint').textContent=state.setupMode?'首次使用，请设置管理员密码。':'请输入管理员密码。';if(Api.getToken()){try{await Api.check();showMain();await refreshAll()}catch(e){Api.clearToken()}}}catch(e){$('#login-hint').textContent='认证检测失败：'+e.message}}
async function doLogin(){const p=$('#login-password').value,p2=$('#login-password2').value;$('#login-error').textContent='';try{if(state.setupMode){if(p.length<8)throw new Error('密码至少 8 位');if(p!==p2)throw new Error('两次密码不一致');const r=await Api.setup(p);Api.setToken(r.token)}else{const r=await Api.login(p);Api.setToken(r.token)}showMain();await refreshAll()}catch(e){$('#login-error').textContent=e.message}}
async function loadConfig(){state.config=await Api.config();state.config.sources=Array.isArray(state.config.sources)?state.config.sources:[]}
async function loadInfo(){try{state.info=await Api.info()}catch(e){state.info={error:e.message}}}
async function loadStatus(){try{state.status=await Api.backupStatus()}catch(e){state.status={error:e.message}}}
async function loadBackups(){try{const r=await Api.backups();state.backups=r.backups||[]}catch(e){state.backups=[]}}
async function loadRestore(){try{const r=await Api.restoreList();state.restoreBackups=r.backups||[]}catch(e){state.restoreBackups=state.backups||[]}}
async function loadAgents(){try{state.agents=await Api.qwenpawDashboard()}catch(e){state.agents={error:e.message,cards:[]}}}
async function loadLogs(){try{const r=await Api.logs('server',80);const box=$('#logs-box');if(box)box.textContent=(r.lines||[]).join('\n')||'暂无日志'}catch(e){const box=$('#logs-box');if(box)box.textContent='日志读取失败：'+e.message}}
function renderAll(){renderHome();renderSources('backup-sources');renderSources('schedule-sources');renderSchedule();renderBackups();renderRestore();renderAgents();renderSettings();renderStatus();renderBackupResult()}
function renderStatus(){const s=state.status||{};const run=state.lastBackupRun;const status=$('#backup-status'),title=$('#backup-run-title'),btn=$('#start-backup-btn'),card=$('#backup-run-card');if(!status)return;if(run&&run.running){status.textContent=run.message||`正在备份：${s.sourceName||s.phase||'处理中'} · ${s.percent||0}%`;if(title)title.textContent='备份进行中';if(btn){btn.disabled=true;btn.textContent='备份中...'}if(card)card.classList.add('running');return}if(run&&!run.running){if(run.error){if(title)title.textContent='备份失败';status.textContent=run.error}else{const count=(run.newBackups||[]).length;if(title)title.textContent='备份完成';status.textContent=`成功生成 ${count} 份备份，失败 ${Math.max(0,Number(run.sourceCount||count)-count)} 份。`}if(btn){btn.disabled=false;btn.textContent='开始备份'}if(card)card.classList.remove('running');return}if(s.running){status.textContent=`正在备份：${s.sourceName||s.phase||'处理中'} · ${s.percent||0}%`;if(title)title.textContent='备份进行中';if(btn){btn.disabled=true;btn.textContent='备份中...'}if(card)card.classList.add('running')}else{if(title)title.textContent='准备就绪';status.textContent='选择内容后点击开始备份。';if(btn){btn.disabled=false;btn.textContent='开始备份'}if(card)card.classList.remove('running')}} 
function renderHome(){const src=enabledSources(),latest=state.backups[0],sch=(state.config&&state.config.schedule)||{};const hs=$('#home-status');if(hs)hs.innerHTML=`<div><span>备份内容</span><b>${src.length} 项</b></div><div><span>定时</span><b>${sch.enabled?'已开启':'未开启'}</b></div><div><span>备份库</span><b>${state.backups.length} 份</b></div>`;const bh=$('#home-backup-hint');if(bh)bh.textContent=src.length?`已选择 ${src.length} 项内容`:'还未选择内容';const sh=$('#home-schedule-hint');if(sh)sh.textContent=sch.enabled?describeCron(sch.cron):'未开启';const rh=$('#home-restore-hint');if(rh)rh.textContent=latest?`最近：${fmtTime(latest.createdAt||latest.mtime||latest.time||latest.timestamp)}`:'暂无备份';const srcBox=$('#home-sources');if(srcBox)srcBox.innerHTML=src.length?src.map(s=>`<div><b>${esc(s.name)}</b><small>${esc(s.path)}</small></div>`).join(''):'<p class="empty">还没有选择备份内容。</p>';const backBox=$('#home-backups');if(backBox)backBox.innerHTML=state.backups.length?state.backups.slice(0,4).map(backupRowMini).join(''):'<p class="empty">暂无备份。</p>'}
function describeCron(cron){const a=String(cron||'0 3 * * *').trim().split(/\s+/);const t=String(a[1]||'3').padStart(2,'0')+':'+String(a[0]||'0').padStart(2,'0');if(a[2]&&a[2]!=='*')return `每月 ${a[2]} 日 ${t}`;if(a[4]&&a[4]!=='*')return `每周${'日一二三四五六'[parseInt(a[4])||0]} ${t}`;return `每天 ${t}`}
function renderSources(id){const box=$('#'+id);if(!box||!state.config)return;const arr=allSources();box.innerHTML=arr.length?arr.map(s=>`<label class="check-item"><input type="checkbox" data-source="${esc(s.id)}" ${s.enabled?'checked':''}><span>${sourceLabel(s)}</span></label>`).join(''):'<p class="empty">还没有备份内容。</p>';$$('input[data-source]',box).forEach(cb=>cb.onchange=()=>{const s=allSources().find(x=>x.id===cb.dataset.source);if(s)s.enabled=cb.checked;renderHome()});const hint=$('#no-source-hint');if(hint)hint.classList.toggle('hidden',arr.length>0&&enabledSources().length>0)}
function renderSchedule(){if(!state.config)return;const sch=state.config.schedule||{};$('#schedule-enabled').checked=!!sch.enabled;cronToUi(sch.cron||'0 3 * * *');$('#keep-last').value=(state.config.retention&&state.config.retention.keepLast)||10;$('#schedule-status').textContent=sch.enabled?'当前已开启':'当前未开启'}
function backupRowMini(item){return `<div class="mini-item"><b>${esc(item.name||item.id||item.filename)}</b><small>${fmtTime(item.createdAt||item.mtime||item.time||item.timestamp)} · ${fmtSize(item.size||item.bytes||0)}</small></div>`}
function backupCard(item,restoreMode){const id=backupId(item);return `<article class="backup-card"><div><h3>${esc(item.name||item.filename||id)}</h3><p>${fmtTime(item.createdAt||item.mtime||item.time||item.timestamp)} · ${fmtSize(item.size||item.bytes||0)}</p><small>${esc(item.sourceName||item.source||item.status||'备份')}</small></div><div class="card-actions"><button class="btn soft" data-detail="${esc(id)}">详情</button>${restoreMode?`<button class="btn primary" data-restore="${esc(id)}">恢复</button>`:`<button class="btn soft" data-download="${esc(id)}">下载</button><button class="btn danger" data-delete="${esc(id)}">删除</button>`}</div></article>`}
function renderBackups(){const box=$('#backup-list');if(!box)return;box.innerHTML=state.backups.length?state.backups.map(x=>backupCard(x,false)).join(''):'<div class="empty big">暂无备份。去“备份”页面创建第一份。</div>';bindBackupButtons(box)}
function renderRestore(){const box=$('#restore-list');if(!box)return;const arr=state.restoreBackups.length?state.restoreBackups:state.backups;box.innerHTML=arr.length?arr.map(x=>backupCard(x,true)).join(''):'<div class="empty big">暂无可恢复备份。先创建备份。</div>';bindBackupButtons(box)}
function renderAgents(){const summary=$('#agent-summary'),box=$('#agent-list');if(!summary||!box)return;const data=state.agents;if(!data){summary.textContent='加载中...';box.textContent='加载中...';return}if(data.error){summary.innerHTML=`<div class="empty big">智能体读取失败：${esc(data.error)}</div>`;box.innerHTML='';return}const cards=data.cards||[];summary.innerHTML=`<div><span>发现智能体</span><b>${cards.length}</b></div><div><span>有记忆文件</span><b>${cards.filter(c=>c.coreFiles>0||c.memDays>0).length}</b></div><div><span>最近备份覆盖</span><b>${cards.filter(c=>c.lastBackup).length}</b></div>`;box.innerHTML=cards.length?cards.map(c=>`<article class="agent-card"><div class="agent-name"><b>Agent ${esc(c.agent)}</b><span>${c.lastBackup?'已备份':'未单独备份'}</span></div><div class="agent-meta"><div><small>核心文件</small><b>${c.coreFiles||0}</b></div><div><small>记忆日记</small><b>${c.memDays||0}</b></div><div><small>笔记</small><b>${c.notes||0}</b></div><div><small>大小</small><b>${esc(c.memDirSizeHuman||c.coreSizeHuman||'-')}</b></div></div><p>MEMORY 更新时间：${fmtTime(c.memoryMtime)}</p><p>最近备份：${c.lastBackup?fmtTime(c.lastBackup.at):'暂无'}</p></article>`).join(''):'<div class="empty big">未发现智能体工作区。</div>'}
function renderSettings(){if(!state.config)return;const st=state.config.storage||{},nt=state.config.notify||{};const storageBox=$('#storage-settings');if(storageBox)storageBox.innerHTML=`<label>备份保存位置<input id="storage-root" value="${esc(st.root||'')}"></label><label>回收站保留天数<input id="trash-days" type="number" min="1" value="${esc(st.trashDays||7)}"></label><label>保留最近几份<input id="ret-keep" type="number" min="1" value="${esc((state.config.retention&&state.config.retention.keepLast)||10)}"></label>`;const notifyBox=$('#notify-settings');if(notifyBox)notifyBox.innerHTML=`<label class="switch-line"><span><b>通知</b><small>备份成功/失败时通知。</small></span><input id="notify-enabled" type="checkbox" ${nt.enabled?'checked':''}></label><label>QQ Webhook<input id="notify-qq" value="${esc(nt.channels&&nt.channels.qq&&nt.channels.qq.url||'')}" placeholder="可选"></label>`}
function collectSourceChecks(containerId){$$(`#${containerId} input[data-source]`).forEach(cb=>{const s=allSources().find(x=>x.id===cb.dataset.source);if(s)s.enabled=cb.checked})}
async function applyRecommended(){state.config.sources=clone(REC_SOURCES);await Api.saveConfig(state.config);toast('已选择推荐备份内容','ok');await loadConfig();renderAll()}
async function saveCurrentConfig(){collectSourceChecks('backup-sources');collectSourceChecks('schedule-sources');await Api.saveConfig(state.config);toast('已保存','ok');await loadConfig();renderAll()}
function renderBackupResult(){const box=$('#backup-result');if(!box)return;const run=state.lastBackupRun;if(!run){box.classList.add('hidden');return}box.classList.remove('hidden');if(run.running){box.className='backup-result running';box.innerHTML=`<h3>备份中</h3><p>${esc(run.message||'正在处理备份任务，请稍候。')}</p><div class="progress-line"><div style="width:${Math.max(5,Math.min(100,Number(run.percent||5)))}%"></div></div>`;return}if(run.error){box.className='backup-result error';box.innerHTML=`<h3>备份失败</h3><p>${esc(run.error)}</p><div class="btn-row"><button class="btn soft" data-go="more">查看日志</button><button class="btn primary" id="backup-again-btn">重新备份</button></div>`;const b=$('#backup-again-btn');if(b)b.onclick=runBackup;$$('[data-go]',box).forEach(b=>b.onclick=()=>go(b.dataset.go));return}const items=run.newBackups||[], expected=Number(run.sourceCount||items.length||0), fail=Math.max(0,expected-items.length);box.className='backup-result '+(fail?'error':'ok');box.innerHTML=`<h3>${fail?'备份完成（部分成功）':'备份完成'}</h3><p>成功生成 ${items.length} 份备份，失败 ${fail} 份。</p>${items.length?`<div class="result-list">${items.map(backupRowMini).join('')}</div>`:''}${fail?'<p class="warn-text">有备份项没有生成新备份，请在“更多”里查看日志。</p>':''}<div class="btn-row"><button class="btn primary" data-go="more">查看备份库</button><button class="btn soft" id="backup-again-btn">继续备份</button></div>`;const b=$('#backup-again-btn');if(b)b.onclick=runBackup;$$('[data-go]',box).forEach(b=>b.onclick=()=>go(b.dataset.go))}
async function runBackup(){try{collectSourceChecks('backup-sources');if(!enabledSources().length){toast('请先选择至少一个备份内容','error');return}await Api.saveConfig(state.config);const before=new Set(state.backups.map(backupId));const ids=enabledSources().map(s=>s.id);state.lastBackupRun={running:true,beforeIds:before,startedAt:Date.now(),sourceCount:ids.length,percent:5,message:`已提交 ${ids.length} 项备份内容。`};renderStatus();renderBackupResult();await Api.runBackup({sourceIds:ids,manual:true});toast('备份已开始','ok');pollBackup()}catch(e){state.lastBackupRun={running:false,error:e.message};renderStatus();renderBackupResult();toast('备份失败：'+e.message,'error')}}
async function pollBackup(){if(state.polling)return;state.polling=true;try{let last={},idleSeen=0;const run=state.lastBackupRun;const expected=run&&Number(run.sourceCount||0);for(let i=0;i<120;i++){await new Promise(r=>setTimeout(r,2000));await loadStatus();last=state.status||{};await loadBackups();const before=state.lastBackupRun&&state.lastBackupRun.beforeIds||new Set();const added=state.backups.filter(b=>!before.has(backupId(b)));if(state.lastBackupRun&&state.lastBackupRun.running){state.lastBackupRun.percent=last.percent||state.lastBackupRun.percent;state.lastBackupRun.newBackups=added;state.lastBackupRun.message=last.running?`正在处理：${last.sourceName||last.phase||'备份任务'} · ${last.percent||0}%`:`已生成 ${added.length}/${expected||added.length} 份，正在确认任务是否结束...`}renderStatus();renderBackupResult();if(!last.running){idleSeen+=1;if((expected&&added.length>=expected)||idleSeen>=5)break}else idleSeen=0}await loadBackups();const before=state.lastBackupRun&&state.lastBackupRun.beforeIds||new Set();const added=state.backups.filter(b=>!before.has(backupId(b)));if(state.lastBackupRun){state.lastBackupRun.running=false;if(last&&last.error)state.lastBackupRun.error=last.error;else state.lastBackupRun.newBackups=added}renderStatus();renderAll();if(!state.lastBackupRun.error)toast(`备份完成：生成 ${added.length} 份备份`,'ok')}finally{state.polling=false}}
async function saveSchedule(){try{collectSourceChecks('schedule-sources');if(!enabledSources().length){toast('请先选择定时备份内容','error');return}state.config.schedule={enabled:$('#schedule-enabled').checked,cron:uiToCron()};state.config.retention=state.config.retention||{};state.config.retention.keepLast=Math.max(1,parseInt($('#keep-last').value)||10);await Api.saveConfig(state.config);toast('定时设置已保存','ok');await refreshAll()}catch(e){toast('保存定时失败：'+e.message,'error')}}
async function saveStorage(){try{state.config.storage=state.config.storage||{};state.config.retention=state.config.retention||{};state.config.storage.root=$('#storage-root').value.trim();state.config.storage.trashDays=Math.max(1,parseInt($('#trash-days').value)||7);state.config.retention.keepLast=Math.max(1,parseInt($('#ret-keep').value)||10);await Api.saveConfig(state.config);toast('存储设置已保存','ok')}catch(e){toast(e.message,'error')}}
async function saveNotify(){try{state.config.notify=state.config.notify||{};state.config.notify.channels=state.config.notify.channels||{};state.config.notify.channels.qq=state.config.notify.channels.qq||{};state.config.notify.enabled=$('#notify-enabled').checked;state.config.notify.channels.qq.url=$('#notify-qq').value.trim();state.config.notify.channels.qq.enabled=!!state.config.notify.channels.qq.url;await Api.saveConfig(state.config);toast('通知设置已保存','ok')}catch(e){toast(e.message,'error')}}
async function showDetail(id){try{const r=await Api.backupDetail(id);modal(`<h2>备份详情</h2><pre>${esc(JSON.stringify(r.backup||r,null,2))}</pre>`)}catch(e){toast(e.message,'error')}}
async function restoreBackup(id){modal(`<h2>恢复备份</h2><p>将恢复备份：<b>${esc(id)}</b></p><label>恢复到目录<input id="restore-target" value="/vol3/@appshare/com.dustinky.qwenpaw/.qwenpaw/workspaces"></label><p class="warn-text">恢复会覆盖目标目录中的同名文件。确认后执行。</p><button id="do-restore" class="btn primary">确认恢复</button>`);$('#do-restore').onclick=async()=>{try{const target=$('#restore-target').value.trim();await Api.executeRestore(id,target,'');closeModal();toast('恢复已执行','ok')}catch(e){toast('恢复失败：'+e.message,'error')}}}
async function deleteBackup(id){if(!confirm('确认删除这份备份？\n'+id))return;try{await Api.moveTrash(id);toast('已移入回收站','ok');await loadBackups();renderAll()}catch(e){toast(e.message,'error')}}
function bindBackupButtons(root){$$('[data-detail]',root).forEach(b=>b.onclick=()=>showDetail(b.dataset.detail));$$('[data-restore]',root).forEach(b=>b.onclick=()=>restoreBackup(b.dataset.restore));$$('[data-download]',root).forEach(b=>b.onclick=()=>Api.download(b.dataset.download).catch(e=>toast(e.message,'error')));$$('[data-delete]',root).forEach(b=>b.onclick=()=>deleteBackup(b.dataset.delete))}
async function refreshAll(){hideBanner();await Promise.allSettled([loadConfig(),loadInfo(),loadStatus(),loadBackups()]);if(state.current==='agents')await loadAgents();if(state.current==='restore')await loadRestore();if(state.current==='more')await loadLogs();renderAll()}
function bind(){ $$('.nav-item').forEach(b=>b.onclick=()=>go(b.dataset.page));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$('#mobile-menu').onclick=()=>$('.side').classList.toggle('open');$('#refresh-btn').onclick=()=>refreshAll().then(()=>toast('已刷新','ok'));$('#login-btn').onclick=doLogin;$('#login-password').addEventListener('keydown',e=>{if(e.key==='Enter')doLogin()});$('#modal-close').onclick=closeModal;$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});$('#recommend-btn').onclick=applyRecommended;$('#start-backup-btn').onclick=runBackup;$('#save-schedule-btn').onclick=saveSchedule;['schedule-enabled','schedule-frequency','schedule-weekday','schedule-day','schedule-time'].forEach(id=>$('#'+id).addEventListener('change',updateScheduleFields));$('#save-storage-btn').onclick=saveStorage;$('#save-notify-btn').onclick=saveNotify;$('#export-config-btn').onclick=()=>Api.exportConfig().catch(e=>toast(e.message,'error'));$('#import-config-input').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const txt=await f.text();await Api.importConfig(JSON.parse(txt));toast('配置已导入','ok');await refreshAll()}catch(err){toast('导入失败：'+err.message,'error')}}}
window.App={showLogin,togglePwd,go,refreshAll};
document.addEventListener('DOMContentLoaded',()=>{bind();initAuth()});
})();
